config/routes.rb
EmergeDataValidation::Application.routes.draw do
  resources :submissions

  namespace :api do
    namespace :v1 do
      resources :submissions, :only => [:index, :create] do
        post :create_local, :on => :collection
      end
    end
  end

  root :to => 'submissions#new'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
end

app/controllers/api/v1/api_controller.rb
##
# Base controller for all /api/ requests
class Api::V1::ApiController < ActionController::Base
end

app/controllers/api/v1/submissions_controller.rb
require 'validation/file_processor'
require 'validation/data_dictionary_validator'
require 'validation/data_file_validator'
require 'json'

##
# API controller for Submissions
class Api::V1::SubmissionsController < Api::V1::ApiController
  include SubmissionsHelper

  def create
    get_data_from_params(params[:data_dictionary], params[:data_dictionary].original_filename,
      params[:data_file], (params[:data_file] ? params[:data_file].original_filename : nil))
    respond_to do |format|
      format.json { render :json => { :dictionary_file => @data_dictionary_results, :data_file => @data_file_results }.to_json }
      format.html { render "submissions/report"}
    end
  end

  def create_local
    dd_file = File.open(params[:data_dictionary], "r") if params[:data_dictionary]
    data_file = File.open(params[:data_file], "r") if params[:data_file]
    get_data_from_params(dd_file, params[:data_dictionary], data_file, params[:data_file])
    respond_to do |format|
      format.json { render :json => { :dictionary_file => @data_dictionary_results, :data_file => @data_file_results }.to_json }
      format.html { render "submissions/report"}
    end
  end

  def index
    render :layout => "application"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/submissions_controller.rb
require 'validation/file_processor'
require 'validation/data_dictionary_validator'
require 'validation/data_file_validator'

class SubmissionsController < ApplicationController
  include SubmissionsHelper

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/new
  # GET /submissions/new.json
  def new
    @submission = Submission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)
    get_data_from_params(params[:submission][:data_dictionary], params[:submission][:data_dictionary].original_filename,
      params[:submission][:data_file], (params[:submission][:data_file] ? params[:submission][:data_file].original_filename : nil))
    render "report"
  end

  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    @submission = Submission.find(params[:id])

    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end

  private

  def submission_params
    params.require(:submission).permit(:data_dictionary, :data_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def get_data_from_params data_dictionary_param, data_dictionary_name, data_file_param, data_file_name
    data_dictionary = data_dictionary_param.read unless data_dictionary_param.blank?
    data_file = data_file_param.read unless data_file_param.blank?

    unless data_dictionary.blank?
      dd_processor = EMERGE::Phenotype::DataDictionaryValidator.new data_dictionary, :csv, ValidationParameters['error_limit']
      @data_dictionary_results = dd_processor.validate
      @data_dictionary_results[:file_name] = data_dictionary_name
      unless data_file.blank?
        df_processor = EMERGE::Phenotype::DataFileValidator.new data_file, dd_processor.variables, :csv, ValidationParameters['error_limit']
        @data_file_results = df_processor.validate
        @data_file_results[:file_name] = data_file_name
      end
    end
  end

  def results_collection_has_data? collection
    collection.any?{ |x| x[1].length > 0}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eMERGE Data Validation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/submissions/_form.html.haml
= form_for @submission, :html => {:multipart=>true} do |f|
  - if @submission.errors.any?
    #error_explanation
      %h2= "#{pluralize(@submission.errors.count, "error")} prohibited this submission from being saved:"
      %ul
        - @submission.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :data_dictionary
    = f.file_field :data_dictionary
  .field
    = f.label :data_file
    = f.file_field :data_file
  .actions
    = f.submit 'Submit'

app/views/submissions/_results.html.haml
- unless results.blank?
  %div.results{:id => title.downcase.tr(' ', '_')}
    %h1= title
    %div
      = "File: #{results[:file_name]}"
    - if results[:warnings].blank? and results[:errors].blank?
      .status.passed
        %ul
          %li No warnings or errors were detected
    = render :partial => "submissions/results_collection", :locals => {:results_collection => results, :collection => :warnings }
    = render :partial => "submissions/results_collection", :locals => {:results_collection => results, :collection => :errors }

app/views/submissions/_results_collection.html.haml
- if results_collection_has_data?(results_collection[collection])
  .message-collection
    %h2=collection.to_s.titleize
    - results_collection[collection].each do |level|
      - unless level[1].length == 0
        - title = level[0].to_s.titleize
        - item_type = title.singularize
        .message-type
          %h3=title
          .status{:class => collection.downcase}
            %ul
              - if level[1].first.is_a?(Array)
                - level[1].sort.each do |item|
                  %li
                    = "#{item_type} #{item[0]}"
                    - if item[1].count == 1
                      = "- #{item[1].first}"
                    - else
                      %ul
                        - item[1].each do |message|
                          %li= message
              - else
                - level[1].each do |item|
                  %li
                    = item

app/views/submissions/edit.html.haml
%h1 Editing submission

= render 'form'

= link_to 'Show', @submission
\|
= link_to 'Back', submissions_path

app/views/submissions/index.html.haml
%h1 Listing submissions

%table
  %tr
    %th Data dictionary
    %th Data file
    %th Content type
    %th Organization
    %th
    %th
    %th

  - @submissions.each do |submission|
    %tr
      %td= submission.data_dictionary
      %td= submission.data_file
      %td= submission.content_type
      %td= submission.organization
      %td= link_to 'Show', submission
      %td= link_to 'Edit', edit_submission_path(submission)
      %td= link_to 'Destroy', submission, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Submission', new_submission_path

app/views/submissions/new.html.haml
%h1 New submission

= render 'form'

app/views/submissions/report.html.haml
= render "submissions/results", {:results => @data_dictionary_results, :title => "Data Dictionary Results" }
= render "submissions/results", {:results => @data_file_results, :title => "Data File Results" }

app/views/submissions/show.html.haml
%p#notice= notice

%p
  %b Data dictionary:
  = @submission.data_dictionary
%p
  %b Data file:
  = @submission.data_file
%p
  %b Content type:
  = @submission.content_type
%p
  %b Organization:
  = @submission.organization

= link_to 'Edit', edit_submission_path(@submission)
\|
= link_to 'Back', submissions_path